version: '3.5'

networks:
  frontend:
    name: frontend
  storage:
    name: storage

volumes:
  data-mongo:

services:
  mongodb:
    image: mongo:4.2
    container_name: local_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - data-mongo:/data/db
      - ./logs/mongodb:/var/log/mongodb
    networks:
      - storage
  accounts:
    image: com.myfintech/account-service:0.0.1-SNAPSHOT
    container_name: account_service
    restart: always
    ports:
      - "8080:8080"
    environment:
      - mongo_connection_string=mongodb://mongodb:27017
    networks:
      - storage
      - frontend