version: '3.5'

networks:
  storage:
    name: storage

volumes:
  data-mongo:

services:
  mongodb:
    image: mongo:4.2
    container_name: local_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - data-mongo:/data/db
      - ./logs/mongodb:/var/log/mongodb
    networks:
      - storage